In [5]:
pip install numpy

In [2]:
import numpy as np

# creating array using numpay

In [6]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [10]:
price = np.array([5,6,7])
price

array([5, 6, 7])

In [12]:
type(food)

numpy.ndarray

In [13]:
type(price)

numpy.ndarray

In [14]:
len(food)

3

In [15]:
len(price)

3

In [17]:
price[2]

7

In [18]:
food[2]

'raita'

In [19]:
price.max()

7

In [20]:
price.mean()

6.0

In [21]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(5)

array([1.11600229e-311, 4.47593816e-091, 7.01413727e-009, 3.74168445e+233,
       3.98220483e+209])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
# for interval of 2
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# for interval of 3
np.arange(2,20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [28]:
#table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [29]:
#specify data type
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
#specify data type
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array function

In [32]:
arr = np.array([10,20,4.5,90,4,3.2])
arr

array([10. , 20. ,  4.5, 90. ,  4. ,  3.2])

In [34]:
arr.sort()
arr

array([ 3.2,  4. ,  4.5, 10. , 20. , 90. ])

In [35]:
arr2 = np.array([20, 20.2,30,40.2])
arr2

array([20. , 20.2, 30. , 40.2])

In [37]:
c = np.concatenate((arr,arr2))
c

array([ 3.2,  4. ,  4.5, 10. , 20. , 90. , 20. , 20.2, 30. , 40.2])

In [39]:
c.sort()
c

array([ 3.2,  4. ,  4.5, 10. , 20. , 20. , 20.2, 30. , 40.2, 90. ])

# 2D_Array

In [41]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
b = np.array([[4,3,2,1], [5,6,7,8]])
b

array([[4, 3, 2, 1],
       [5, 6, 7, 8]])

In [45]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1],
       [5, 6, 7, 8]])

In [46]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1],
       [5, 6, 7, 8]])

In [47]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [49]:
# find dimention or arry
c.ndim

2

In [52]:
a = np.array([[[1,2,3,4], [1,2,3,4]],
            [[1,2,3,4], [1,2,3,4]],
            [[1,2,3,4], [1,2,3,4]]])
a

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [53]:
a.ndim

3

In [56]:
a.size

24

In [57]:
a.shape

(3, 2, 4)

In [63]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [64]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])